import type { Metadata } from "next";
import { Geist, Geist_Mono,Pacifico,Dancing_Script} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400",           // Pacifico only has a Regular (400) weight
  subsets: ["latin"],      // specify necessary language subsets
  variable: "--font-pacifico",  // CSS variable reference
  display: "swap",         // better rendering experience
});

const dancing = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],   // load the weights you’ll use
  display: "swap",
  variable: "--font-dancing",             // CSS var
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} ${dancing.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
